// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(CustomerServiceContext))]
    [Migration("20260422154422_UpdateCompanyPathAndCallSchema")]
    partial class UpdateCompanyPathAndCallSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallId"));

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<double?>("CustomerMaxVolume")
                        .HasColumnType("float");

                    b.Property<double?>("CustomerSentimentEnd")
                        .HasColumnType("float");

                    b.Property<double?>("CustomerSentimentStart")
                        .HasColumnType("float");

                    b.Property<string>("CustomerTranscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<double?>("OperatorMaxVolume")
                        .HasColumnType("float");

                    b.Property<string>("OperatorSentiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorTranscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OperatorWordsPerSecond")
                        .HasColumnType("float");

                    b.HasKey("CallId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Repository.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("AudioFolderRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntroPhrase")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<double?>("DailyScore")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MonthlyScore")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Repository.Entities.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("CallId")
                        .HasColumnType("int");

                    b.Property<double?>("ConflictResolutionScore")
                        .HasColumnType("float");

                    b.Property<int?>("ImprovementTips")
                        .HasColumnType("int");

                    b.Property<double?>("OperatorToneScore")
                        .HasColumnType("float");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double?>("ProfessionalismScore")
                        .HasColumnType("float");

                    b.HasKey("ScoreId");

                    b.HasIndex("CallId")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.HasOne("Repository.Entities.Company", "Company")
                        .WithMany("Calls")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Operator", "Operator")
                        .WithMany("Calls")
                        .HasForeignKey("OperatorId");

                    b.Navigation("Company");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.HasOne("Repository.Entities.Company", "Company")
                        .WithMany("Operators")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Repository.Entities.Score", b =>
                {
                    b.HasOne("Repository.Entities.Call", "Call")
                        .WithOne("Score")
                        .HasForeignKey("Repository.Entities.Score", "CallId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("Repository.Entities.Call", b =>
                {
                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.Company", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Operators");
                });

            modelBuilder.Entity("Repository.Entities.Operator", b =>
                {
                    b.Navigation("Calls");
                });
#pragma warning restore 612, 618
        }
    }
}
